
name: Try build 

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '15 10 * * 5'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Install Pub Dependencies
        run: dart pub get

      - name: Install WebDev
        run: dart pub global activate webdev && export PATH="$PATH":"$HOME/.pub-cache/bin"

      - name: Build
        run: webdev build
